### ISSUE TITLE
Error while building: point_cloud2_iterator.hpp not found

### ISSUE THREAD

**Issue by amansrf** [NVIDIA-AI-IOT/ros2_tao_pointpillars#1]
`fatal error: ../include/pp_infer/point_cloud2_iterator.hpp: No such file or directory
   46 | #include "../include/pp_infer/point_cloud2_iterator.hpp"
`

Where can I find this file? @AsawareeBhide 

[EDIT] Is it just this file: https://github.com/ros2/common_interfaces/blob/foxy/sensor_msgs/include/sensor_msgs/point_cloud2_iterator.hpp

[EDIT #2]: Looks like it is that file. I wonder why we need to include it seperately like this? Any reason?

**Comment by RFRIEDM-Trimble** [comment]
`sensor_msgs` is included in the `package.xml`, but not linked in the CMakeLists. Fixing the linkage and includes uncovered another issue, but I fixed that too on my fork.

**Comment by amansrf** [comment]
That makes sense. Will take a look at your fork.

What was the other issue you found?

**Comment by RFRIEDM-Trimble** [comment]
> That makes sense. Will take a look at your fork.
> 
> What was the other issue you found?

I'll file a ticket for it shortly.

**Comment by MathiasPechinger** [comment]
@RFRIEDM-Trimble I am using your fork and still get the "no such file" error concerning the "point_cloud2_interator.hpp" file. I am using your bugfix branch. Are you sure your fork up to date?
